### ISSUE TITLE
CRLF cause plugin not work on macOS/Linux environment

### ISSUE THREAD

**Issue by jonz94** [mapkts/enwise#1]
First of all, thanks for creating this amazing plugin 👍.
Your idea of only add missing pair after pressing `Enter` is so brilliant and mind blowing for me 😂.

I currently have an issue when using this plugin on `macOS` or `Linux` environment. I got this error message whenever I open vim:
```
Error detected while processing /home/jonz94/.local/share/nvim/plugged/enwise/plugin/enwise.vim:
line    1:
E15: Invalid expression: !get(g:, "enwise_enable_globally")^M
line   42:
E171: Missing :endif
```

I think the issue is cause by `CRLF` (show as `^M` in the error message), and could be solved by changing `CRLF` to `LF`.

**Comment by mapkts** [comment]
Thanks for pointing out and fixing this issue! 

And thanks for your appreciation for this immature plugin!

Don't know why I have committed those damn CRLFs though 😂.
