### ISSUE TITLE
Enwise don't work until toggle it 2 times at start up.

### ISSUE THREAD

**Issue by NDK2020** [mapkts/enwise#3]
The Enwise don't work with my vim as start up time. Even I've checked the Enwise having enabled by default, I have to call ":EnwiseToggle" 2 time to make it work as normal.

Here some of my system info:

> Vim 8.2 patch 1-2846 
> Kitty_Terminal
> OS: MX Linux KDE  v19

**Comment by mapkts** [comment]
It seems weird. Could you provide your vimrc settings?

**Comment by NDK2020** [comment]
Dear,

Here is my .vimrc, it's pretty long but may be all the general settings is from line 254 to the start of file, and the rest are custom configs for other plugins. 

> https://pastebin.pl/view/c07546b9

Thanks you for the brilliant idea of "Enter" to close brackets
Have a nice day .

**Comment by mapkts** [comment]
I have just made an update to this plugin. Could you run `:PlugUpdate` and check if it works?

If it still doesn't work as expected, run `:verbose imap <CR>` in vim and check if the output is something similar to

```text
i  <CR>          <CR><Plug>(EnwiseClose)
        Last set from ~\.vim\plugged\enwise\autoload\enwise.vim line 14
```

**Comment by NDK2020** [comment]
Dear,

As you expected. after I run `:verbose imap <CR>`
> i  <CR>        * pumvisible() ? coc#_select_confirm(): "\<C-G>u\<CR>\<C-R>=coc#on_enter()\<CR>"

I forgot to mention that I have remap the Enter in Insert Mode to confirm selection in coc.nvim. 
https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources
I will assign another key to adapt this conflict.

Thanks,

**Comment by mapkts** [comment]
Good. I would consider this issue resolved and close this now.

**Comment by NDK2020** [comment]
Dear,

I add solution for those who want to use Enter key for both completion task of coc.nvim and Enwise in Insert mode.

in .vimrc
```
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<Down>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<up>" : "\<c-h>"

if exists('*complete_info')

  inoremap <silent><expr> <cr> complete_info(['selected'])['selected'] != -1 ? "\<C-y>" : "\<C-g>u\<CR>"
"remap Enwise after finishing competion move
  imap <CR> <CR><Plug>(EnwiseClose)

endif
```
